---
- name: Ajouter un utilisateur sur Ubuntu
  hosts: all
  become: yes
  become_method: sudo
  become_user: bainailyas  # Utilisateur sous lequel les commandes seront exécutées après élévation
  vars:
    ansible_become_pass: "Btissam1970$"  # Mot de passe sudo
  tasks:
    - name: Créer un nouvel utilisateur avec mot de passe
      user:
        name: newuser
        state: present
        shell: /bin/bash
        password: "Btissam1970$"  # Remplacez ceci par le mot de passe crypté
