---
- name: Playbook pour créer un dossier dans /home/bainailyas
  hosts: all
  become: yes
  become_method: sudo
  become_user: bainailyas
  vars:
    ansible_become_pass: "Btissam1970$"

  tasks:
    - name: Créer un dossier dans /home/bainailyas
      file:
        path: /home/ilyasbainam10/mon_nouveau_dossier
        state: directory
        mode: '0755'
