- name: Install Google Chrome on Windows
  hosts: windows
  tasks:
    - name: Ensure the Temp directory exists
      ansible.windows.win_file:
        path: C:\Temp
        state: directory

    - name: Download Google Chrome installer
      ansible.windows.win_get_url:
        url: https://dl.google.com/chrome/install/latest/chrome_installer.exe
        dest: C:\Temp\chrome_installer.exe

    - name: Install Google Chrome
      ansible.windows.win_command:
        cmd: C:\Temp\chrome_installer.exe /silent /install
        # No become is needed here
      args:
        chdir: C:\Temp

    - name: Create a shortcut on the desktop
      ansible.windows.win_shell: |
        $shortcut = "$env:USERPROFILE\Desktop\Google Chrome.lnk"
        $targetPath = "C:\Program Files\Google\Chrome\Application\chrome.exe"
        $wshShell = New-Object -ComObject WScript.Shell
        $shortcutObj = $wshShell.CreateShortcut($shortcut)
        $shortcutObj.TargetPath = $targetPath
        $shortcutObj.Save()
      # No become is needed here
