---
- name: Install Google Chrome on Windows and create a desktop shortcut
  hosts: windows
  tasks:
    - name: Download Google Chrome Installer
      ansible.windows.win_get_url:
        url: https://dl.google.com/chrome/install/latest/chrome_installer.exe
        dest: C:\Temp\chrome_installer.exe

    - name: Install Google Chrome
      ansible.windows.win_command:
        cmd: C:\Temp\chrome_installer.exe /silent /install
      become: yes

    - name: Ensure Google Chrome is installed
      ansible.windows.win_stat:
        path: C:\Program Files\Google\Chrome\Application\chrome.exe
      register: chrome_installed

    - name: Create shortcut for Google Chrome on Desktop
      ansible.windows.win_shell: |
        if (Test-Path -Path "C:\Program Files\Google\Chrome\Application\chrome.exe") {
          $shell = New-Object -ComObject WScript.Shell
          $shortcut = $shell.CreateShortcut("$env:USERPROFILE\Desktop\Google Chrome.lnk")
          $shortcut.TargetPath = "C:\Program Files\Google\Chrome\Application\chrome.exe"
          $shortcut.IconLocation = "C:\Program Files\Google\Chrome\Application\chrome.exe, 0"
          $shortcut.Save()
        }
      when: chrome_installed.stat.exists
