- name: Test Playbook
  hosts: all
  tasks:
    - name: Test connectivity
      ansible.builtin.ping:

    - name: Install nginx on Linux
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install IIS on Windows
      win_feature:
        name: Web-Server
        state: present
      when: ansible_os_family == "Windows"
      notify:
        - Start IIS

  handlers:
    - name: Start IIS
      win_service:
        name: W3SVC
        state: started
        start_mode: auto
      when: ansible_os_family == "Windows"

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
