---
- name: Assurer les mises à jour sur les VMs Ubuntu et Windows
  hosts: all
  become: yes
  tasks:
    - name: Mises à jour sur Ubuntu
      block:
        - name: Mettre à jour la liste des paquets APT sur Ubuntu
          apt:
            update_cache: yes

        - name: Mettre à jour tous les paquets sur Ubuntu
          apt:
            upgrade: dist
            autoremove: yes
            autoclean: yes

        - name: Redémarrer Ubuntu si nécessaire
          reboot:
            msg: "Redémarrage après la mise à jour d'Ubuntu"
            pre_reboot_delay: 5
            test_command: whoami

      when: ansible_facts['os_family'] == "Debian"

    - name: Mises à jour sur Windows
      block:
        - name: Assurer les mises à jour Windows
          win_updates:
            category_names: "{{ update_categories | default([]) }}"
            reboot: true
            log_path: C:\Windows\Temp\update_log.txt

        - name: Créer un fichier de log de test
          win_copy:
            content: "Ceci est un fichier de log de test."
            dest: C:\Windows\Temp\update_log.txt

      when: ansible_facts['os_family'] == "Windows"
